// [assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETCoreApp,Version=v8.0", FrameworkDisplayName = ".NET 8.0")]
// [assembly: System.Reflection.AssemblyMetadata("IsTrimmable", "True")]
// [assembly: System.Reflection.AssemblyCompanyAttribute("Microsoft Corporation")]
// [assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
// [assembly: System.Reflection.AssemblyCopyrightAttribute("© Microsoft Corporation. All rights reserved.")]
// [assembly: System.Reflection.AssemblyFileVersionAttribute("42.42.42.42424")]
// [assembly: System.Reflection.AssemblyInformationalVersionAttribute("8.0.0")]
// [assembly: System.Reflection.AssemblyProductAttribute("Microsoft® .NET")]
// [assembly: System.Reflection.AssemblyTitleAttribute("System.Private.CoreLib")]
// [assembly: System.Reflection.AssemblyVersionAttribute("8.0.0.0")]
// [assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/dotnet/runtime")]
